

CREATE TABLE AUDITORIA_CALIFICACION
(
  ID_ACAL NUMBER(8) NOT NULL PRIMARY KEY
, F_ACTUALIZA DATE NOT NULL 
, N_USUARIO VARCHAR2(30) NOT NULL
, ID_REPRESENTANTE NUMBER(8) NOT NULL 
, CALIFICACION_ANT NUMBER(2,1)
, CALIFICACION_NUE NUMBER(2,1)
) ;


CREATE TABLE AUDITORIA_VENTA
(
  ID_AVEN NUMBER(8) NOT NULL PRIMARY KEY
, F_ACTUALIZA DATE NOT NULL 
, N_USUARIO VARCHAR2(30) NOT NULL
, ID_REPRESENTANTE NUMBER(8) NOT NULL  
, VENTA_ANT NUMBER(10,2)
, VENTA_NUE NUMBER(10,2)
);

CREATE TABLE AUDITORIA_COMISION
(
  ID_ACOM NUMBER(8) NOT NULL PRIMARY KEY
, F_ACTUALIZA DATE NOT NULL 
, N_USUARIO VARCHAR2(30) NOT NULL
, ID_CLASIFICACION NUMBER(8) NOT NULL  
, COMISION_ANT NUMBER(10,2) 
, COMISION_NUE NUMBER(10,2) 
);
