
DROP TABLESPACE DEFNATAME INCLUDING CONTENTS AND DATAFILES;

DROP TABLESPACE DEFUSUARIO INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE TEMUSUARIO INCLUDING CONTENTS AND DATAFILES;

DROP USER NATAME CASCADE;

DROP USER CLIENTE CASCADE;

DROP USER REPRESENTANTE CASCADE;

DROP USER ADMINSISTEMA CASCADE;

DROP ROLE R_CLIENTE;

DROP ROLE R_REPRESENTANTE;

DROP ROLE R_ADMINSISTEMA;
