CREATE TABLESPACE DEFNATAME DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\DEFNATAME.DBF' SIZE 6M AUTOEXTEND ON;

CREATE TABLESPACE DEFUSUARIO DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\DEFUSUARIO.DBF' SIZE 6M AUTOEXTEND ON;

CREATE TEMPORARY TABLESPACE TEMUSUARIO TEMPFILE 'C:\oraclexe\app\oracle\oradata\XE\TEMUSUARIO.DBF' SIZE 3M AUTOEXTEND ON;


CREATE USER NATAME IDENTIFIED BY NATAME DEFAULT TABLESPACE DEFNATAME TEMPORARY TABLESPACE TEMUSUARIO;

GRANT CONNECT, RESOURCE TO NATAME;


CREATE USER CLIENTE IDENTIFIED BY CLIENTE DEFAULT TABLESPACE DEFUSUARIO TEMPORARY TABLESPACE TEMUSUARIO;

CREATE USER REPRESENTANTE IDENTIFIED BY REPRESENTANTE DEFAULT TABLESPACE DEFUSUARIO TEMPORARY TABLESPACE TEMUSUARIO;

CREATE USER ADMINSISTEMA IDENTIFIED BY ADMINSISTEMA DEFAULT TABLESPACE DEFUSUARIO TEMPORARY TABLESPACE TEMUSUARIO;