
CREATE ROLE R_CLIENTE;

GRANT SELECT ON CLIENTES TO R_CLIENTE;
GRANT SELECT ON PEDIDOS TO R_CLIENTE;
GRANT SELECT ON VENTAS TO R_CLIENTE;
GRANT SELECT ON PRODUCTOS TO R_CLIENTE;
GRANT SELECT ON REPRESENTANTE_CLIENTES TO R_CLIENTE;
GRANT SELECT, INSERT ON TARJETAS TO R_CLIENTE;
GRANT SELECT, INSERT ON CUENTAS_PSE TO R_CLIENTE;
GRANT UPDATE (TELEFONO,CONTRASENA) ON CLIENTES TO R_CLIENTE;
GRANT INSERT (CALIFICACION) ON PEDIDOS TO R_CLIENTE;

GRANT CONNECT to R_CLIENTE ;

CREATE ROLE R_REPRESENTANTE;
GRANT SELECT ON REPRESENTANTES TO R_REPRESENTANTE;
GRANT SELECT ON UBICACIONES TO R_REPRESENTANTE;
GRANT SELECT ON CLASIFICACIONES TO R_REPRESENTANTE;
GRANT SELECT ON HISTORICO_CLASIFICACIONES TO R_REPRESENTANTE;
GRANT SELECT ON REPRESENTANTE_CLIENTES TO R_REPRESENTANTE;
GRANT SELECT ON PEDIDOS TO R_REPRESENTANTE;
GRANT SELECT ON VENTAS TO R_REPRESENTANTE;
GRANT SELECT ON PRODUCTOS TO R_REPRESENTANTE;
GRANT INSERT ON CLIENTES TO R_REPRESENTANTE;
GRANT UPDATE (TELEFONO,CONTRASENA) ON REPRESENTANTES TO R_REPRESENTANTE;
GRANT CREATE USER TO R_REPRESENTANTE;
GRANT GRANT ANY ROLE  TO R_REPRESENTANTE;
GRANT CONNECT, R_REPRESENTANTE TO REPRESENTANTE;

CREATE ROLE R_ADMINSISTEMA;
GRANT INSERT, SELECT, DELETE ON REPRESENTANTES TO R_ADMINSISTEMA;
GRANT SELECT, DELETE ON CLIENTES TO R_ADMINSISTEMA;
GRANT UPDATE (ID_DIRECTOR) ON UBICACIONES TO R_REPRESENTANTE;
GRANT INSERT, SELECT, UPDATE, DELETE ON PRODUCTOS TO R_ADMINSISTEMA;
GRANT INSERT, SELECT, UPDATE ON PAGOS TO R_ADMINSISTEMA;
GRANT INSERT, SELECT, UPDATE ON INVENTARIOS TO R_ADMINSISTEMA;
GRANT INSERT, SELECT, UPDATE ON CLASIFICACIONES TO R_ADMINSISTEMA;
GRANT INSERT, SELECT, UPDATE ON HISTORICO_CLASIFICACIONES TO R_ADMINSISTEMA;
GRANT INSERT, SELECT, UPDATE ON REPRESENTANTE_CLIENTES TO R_ADMINSISTEMA;
GRANT INSERT, SELECT, UPDATE ON VENTAS TO R_ADMINSISTEMA;
GRANT INSERT, SELECT, UPDATE ON PEDIDOS TO R_ADMINSISTEMA;
GRANT ANY ROLE  TO R_ADMINSISTEMA;

GRANT CREATE PUBLIC SYNONYM TO R_ADMINSISTEMA;

GRANT CREATE USER TO R_ADMINSISTEMA;

GRANT CREATE ROLE TO R_ADMINSISTEMA;

GRANT CONNECT, RESOURCE, R_ADMINSISTEMA TO ADMINSISTEMA;
