CREATE USER Luis IDENTIFIED BY 123456 DEFAULT TABLESPACE DEFUSUARIO TEMPORARY TABLESPACE TEMUSUARIO;
CREATE USER Mayvi IDENTIFIED BY 123456 DEFAULT TABLESPACE DEFUSUARIO TEMPORARY TABLESPACE TEMUSUARIO;
CREATE USER Milton IDENTIFIED BY 123456 DEFAULT TABLESPACE DEFUSUARIO TEMPORARY TABLESPACE TEMUSUARIO;
CREATE USER Sebastian IDENTIFIED BY 123456 DEFAULT TABLESPACE DEFUSUARIO TEMPORARY TABLESPACE TEMUSUARIO;

CREATE USER LaDoris IDENTIFIED BY 123456 DEFAULT TABLESPACE DEFUSUARIO TEMPORARY TABLESPACE TEMUSUARIO;
CREATE USER Duvan IDENTIFIED BY 123456 DEFAULT TABLESPACE DEFUSUARIO TEMPORARY TABLESPACE TEMUSUARIO;


