/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 03-jun.-2018 2:10:53 a. m. 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "CATEGORIA" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "CLASIFICACION" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "CLIENTE" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "DETALLE_PRODUCTO" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "HISTORICO_CLASIFICACION" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "PAGO" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "PEDIDO" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "PRODUCTO" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "PSE" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "REGION_PRODUCTO" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "REP_VENTA_CLIENTE" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "REPRESENTANTE_VENTA" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "TARJETA" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "UBICACION" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

/* Create Tables */

CREATE TABLE  "CATEGORIA"
(
	"ID_CATEGORIA" NUMBER(8) NOT NULL,    -- Identificacion de la categoria
	"NOMBRE" VARCHAR2(30) NOT NULL,    -- Nombre de la categoria o subcategoria
	"SUPERCATEGORIA" NUMBER(8) NULL    -- Codigo de la categoria superior que abarca una subcategoria
)
;

CREATE TABLE  "CLASIFICACION"
(
	"ID_CLASIFICACION" NUMBER(8) NOT NULL,    -- Identificacion de la clasificacion: 1, 2, 3 o 4
	"CATEGORIA" VARCHAR2(3) NOT NULL,    -- Categoria relacionada con la clasificacion:  BEGINNER = BG, JUNIOR = JN, SENIOR = SN, MASTER = MS
	"VALOR_INICIAL" NUMBER(10,2) NOT NULL,    -- Limite inferior de ventas para una determinada categoria
	"VALOR_FINAL" NUMBER(10,2) NOT NULL,    -- Limite superior de ventas para una determinada categoria
	"CALIFICACION_MINIMA" NUMBER(2,1) NOT NULL,    -- Calificacion minima requerida para una determinada categoria
	"FECHA_INICIAL" DATE NOT NULL,    -- Fecha inicial de la duracion de una clasificacion
	"FECHA_FINAL" DATE NULL,    -- Fecha final de la duracion de una clasificacion
	"COMISION" NUMBER(4,2) NOT NULL    -- Porcentaje de pago asociado a una determinada categoria
)
;

CREATE TABLE  "CLIENTE"
(
	"CEDULA_CLIENTE" NUMBER(10) NOT NULL,    -- Identificacion del cliente
	"NOMBRE" VARCHAR2(30) NOT NULL,    -- Nombre del cliente
	"APELLIDO" VARCHAR2(30) NOT NULL,    -- Apellido del cliente
	"TELEFONO" VARCHAR2(10) NULL,    -- Telefono del cliente
	"CONTRASENA" VARCHAR2(10) NOT NULL    -- Contraseña de acceso a la plataforma del cliente
)
;

CREATE TABLE  "DETALLE_PRODUCTO"
(
	"ID_PEDIDO" NUMBER(8) NOT NULL,    -- Codigo del pedido asociado a una venta
	"ID_PRODUCTO" NUMBER(8) NOT NULL,    -- Codigo del producto asociado a una venta
	"CANTIDAD" NUMBER(3) NOT NULL,    -- Cantidad del producto solicitado
	"TOTAL_PRODUCTO" NUMBER(10,2) NOT NULL    -- Valor total por producto y su cantidad
)
;

CREATE TABLE  "HISTORICO_CLASIFICACION"
(
	"CEDULA_REPRESENTANTE" NUMBER(10) NOT NULL,    -- Id del representante de ventas el cual tiene asociado un registro historico
	"ID_CLASIFICACION" NUMBER(8) NOT NULL,    -- Id de la clasificacion asociado a un registro historico
	"CALIFICACION" NUMBER(2,1) NOT NULL,    -- Calificacion ponderada que recibio el representante de ventas durante un periodo
	"VENTA" NUMBER(10,2) NOT NULL    -- Valor de las Ventas totales que hizo el representante de ventas durante un periodo
)
;

CREATE TABLE  "PAGO"
(
	"ID_PAGO" NUMBER(8) NOT NULL,    -- Identificacion del pago
	"FECHA" DATE NOT NULL,    -- Fecha en la cual se hizo el pago
	"ID_TARJETA" NUMBER(8) NULL,    -- Si se pago por este medio, se pone la identificacion de la tarjeta
	"ID_PSE" NUMBER(8) NULL    -- Si se pago por este medio, se pone la identificacion de PSE
)
;

CREATE TABLE  "PEDIDO"
(
	"ID_PEDIDO" NUMBER(8) NOT NULL,    -- Identificacion del pedido
	"CEDULA_CLIENTE" NUMBER(10) NOT NULL,    -- Identificacion del cliente que hace el pedido
	"TOTAL_PEDIDO" NUMBER(10,2) NOT NULL,    -- Total del pedido
	"ID_PAGO" NUMBER(8,2) NOT NULL,    -- Identificacion del pago efectuado
	"ESTADO" VARCHAR2(2) NOT NULL,    -- Estado en el que se encuentra el pedido: EP: en proceso, PG: pagado, ET: entregado
	"FECHA" DATE NOT NULL,    -- Fecha en que se realizo el pedido
	"CALIFICACION" NUMBER(2,1) NULL    -- Calificacion que se le da al representante de ventas despues de hacer el pedido
)
;

CREATE TABLE  "PRODUCTO"
(
	"ID_PRODUCTO" NUMBER(8) NOT NULL,    -- Identificacion del producto
	"NOMBRE" VARCHAR2(30) NOT NULL,    -- Nombre del producto
	"ID_CATEGORIA" NUMBER(8) NOT NULL,    -- Id la categoria a la cual pertenece le producto
	"VALOR" NUMBER(10,2) NOT NULL,    -- Valor unitario del producto
	"DETALLE" VARCHAR2(50) NULL,    -- Detalle del producto
	"IVA" NUMBER(4,2) NOT NULL    -- Iva asociado al producto
)
;

CREATE TABLE  "PSE"
(
	"ID_PSE" NUMBER(8) NOT NULL,    -- Identificacion de PSE
	"CEDULA_CLIENTE" NUMBER(10) NOT NULL,    -- Cedula asociada a una cuenta PSE
	"CONTRASENA" VARCHAR2(10) NOT NULL    -- Contraseña de la cuenta PSE
)
;

CREATE TABLE  "REGION_PRODUCTO"
(
	"ID_UBICACION" NUMBER(8) NOT NULL,    -- Identificacion de la ubicacion asociado a un inventario
	"ID_PRODUCTO" NUMBER(8) NOT NULL,    -- Identificacion del producto asociado a un inventario
	"CANTIDAD" NUMBER(6) NOT NULL,    -- Cantidad del producto en inventario
	"ESTADO" VARCHAR2(10) NULL    -- Estado del producto en Stock: AGOTADO, DISPONIBLE
)
;

CREATE TABLE  "REP_VENTA_CLIENTE"
(
	"CEDULA_CLIENTE" NUMBER(10) NOT NULL,    -- Identificacion del cliente
	"CEDULA_REPRESENTANTE" NUMBER(10) NOT NULL,    -- Identificacion del representante de ventas
	"FECHA_INICIAL" DATE NOT NULL,    -- Fecha inicial del periodo en el cual un cliente tuvo a un determinado representante de ventas
	"FECHA_FINAL" DATE NULL    -- Fecha final del periodo en el cual un cliente tuvo a un determinado representante de ventas
)
;

CREATE TABLE  "REPRESENTANTE_VENTA"
(
	"CEDULA_REPRESENTANTE" NUMBER(10) NOT NULL,    -- Identificacion del representante de ventas
	"NOMBRE" VARCHAR2(30) NOT NULL,    -- Nombre del representante de ventas
	"APELLIDO" VARCHAR2(30) NOT NULL,    -- Apellido del representante de ventas
	"TELEFONO" VARCHAR2(10) NULL,    -- Telefono del representante de ventas
	"CONTRASENA" VARCHAR2(10) NOT NULL,    -- Cotraseña con la cual el representante de ventas se loguea en el sistema
	"ID_UBICACION" NUMBER(8) NOT NULL,    -- Codigo de la region a la cual pertenece el representante de ventas
	"ID_REP_SUPERIOR" NUMBER(8) NULL    -- Codigo del representante de ventas superior que ingreso al representante de ventas
)
;

CREATE TABLE  "TARJETA"
(
	"ID_TARJETA" NUMBER(8) NOT NULL,    -- Identificacion de la tarjeta
	"NUMERO" NUMBER(16) NOT NULL,    -- Numero de identificacion unico ligado a la tarjeta
	"CEDULA_CLIENTE" NUMBER(10) NOT NULL,    -- Cedula del cliente que posee una tarjeta
	"CVC" NUMBER(4) NOT NULL,    --  Codigo de verificación unico de la tarjeta
	"FECHA_VENCIMIENTO" DATE NOT NULL    -- Fecha de caducidad de la tarjeta
)
;

CREATE TABLE  "UBICACION"
(
	"ID_UBICACION" NUMBER(8) NOT NULL,    -- Identificacion de la ubicacion
	"NOMBRE" VARCHAR2(30) NOT NULL,    -- Nombre de la ubicacion
	"ID_SUPER" NUMBER(8) NULL,    -- Codigo del pais al cual pertenece la region
	"ID_DIRECTOR" NUMBER(8) NULL    -- Codigo del representante de ventas con el cargo de director de esa region
)
;

/* Create Comments, Sequences and Triggers for Autonumber Columns */

COMMENT ON COLUMN  "CATEGORIA"."ID_CATEGORIA" IS 'Identificacion de la categoria'
;

COMMENT ON COLUMN  "CATEGORIA"."NOMBRE" IS 'Nombre de la categoria o subcategoria'
;

COMMENT ON COLUMN  "CATEGORIA"."SUPERCATEGORIA" IS 'Codigo de la categoria superior que abarca una subcategoria'
;

COMMENT ON COLUMN  "CLASIFICACION"."ID_CLASIFICACION" IS 'Identificacion de la clasificacion: 1, 2, 3 o 4'
;

COMMENT ON COLUMN  "CLASIFICACION"."CATEGORIA" IS 'Categoria relacionada con la clasificacion:  BEGINNER = BG, JUNIOR = JN, SENIOR = SN, MASTER = MS'
;

COMMENT ON COLUMN  "CLASIFICACION"."VALOR_INICIAL" IS 'Limite inferior de ventas para una determinada categoria'
;

COMMENT ON COLUMN  "CLASIFICACION"."VALOR_FINAL" IS 'Limite superior de ventas para una determinada categoria'
;

COMMENT ON COLUMN  "CLASIFICACION"."CALIFICACION_MINIMA" IS 'Calificacion minima requerida para una determinada categoria'
;

COMMENT ON COLUMN  "CLASIFICACION"."FECHA_INICIAL" IS 'Fecha inicial de la duracion de una clasificacion'
;

COMMENT ON COLUMN  "CLASIFICACION"."FECHA_FINAL" IS 'Fecha final de la duracion de una clasificacion'
;

COMMENT ON COLUMN  "CLASIFICACION"."COMISION" IS 'Porcentaje de pago asociado a una determinada categoria'
;

COMMENT ON COLUMN  "CLIENTE"."CEDULA_CLIENTE" IS 'Identificacion del cliente'
;

COMMENT ON COLUMN  "CLIENTE"."NOMBRE" IS 'Nombre del cliente'
;

COMMENT ON COLUMN  "CLIENTE"."APELLIDO" IS 'Apellido del cliente'
;

COMMENT ON COLUMN  "CLIENTE"."TELEFONO" IS 'Telefono del cliente'
;

COMMENT ON COLUMN  "CLIENTE"."CONTRASENA" IS 'Contraseña de acceso a la plataforma del cliente'
;

COMMENT ON COLUMN  "DETALLE_PRODUCTO"."ID_PEDIDO" IS 'Codigo del pedido asociado a una venta'
;

COMMENT ON COLUMN  "DETALLE_PRODUCTO"."ID_PRODUCTO" IS 'Codigo del producto asociado a una venta'
;

COMMENT ON COLUMN  "DETALLE_PRODUCTO"."CANTIDAD" IS 'Cantidad del producto solicitado'
;

COMMENT ON COLUMN  "DETALLE_PRODUCTO"."TOTAL_PRODUCTO" IS 'Valor total por producto y su cantidad'
;

COMMENT ON COLUMN  "HISTORICO_CLASIFICACION"."CEDULA_REPRESENTANTE" IS 'Id del representante de ventas el cual tiene asociado un registro historico'
;

COMMENT ON COLUMN  "HISTORICO_CLASIFICACION"."ID_CLASIFICACION" IS 'Id de la clasificacion asociado a un registro historico'
;

COMMENT ON COLUMN  "HISTORICO_CLASIFICACION"."CALIFICACION" IS 'Calificacion ponderada que recibio el representante de ventas durante un periodo'
;

COMMENT ON COLUMN  "HISTORICO_CLASIFICACION"."VENTA" IS 'Valor de las Ventas totales que hizo el representante de ventas durante un periodo'
;

COMMENT ON COLUMN  "PAGO"."ID_PAGO" IS 'Identificacion del pago'
;

COMMENT ON COLUMN  "PAGO"."FECHA" IS 'Fecha en la cual se hizo el pago'
;

COMMENT ON COLUMN  "PAGO"."ID_TARJETA" IS 'Si se pago por este medio, se pone la identificacion de la tarjeta'
;

COMMENT ON COLUMN  "PAGO"."ID_PSE" IS 'Si se pago por este medio, se pone la identificacion de PSE'
;

COMMENT ON COLUMN  "PEDIDO"."ID_PEDIDO" IS 'Identificacion del pedido'
;

COMMENT ON COLUMN  "PEDIDO"."CEDULA_CLIENTE" IS 'Identificacion del cliente que hace el pedido'
;

COMMENT ON COLUMN  "PEDIDO"."TOTAL_PEDIDO" IS 'Total del pedido'
;

COMMENT ON COLUMN  "PEDIDO"."ID_PAGO" IS 'Identificacion del pago efectuado'
;

COMMENT ON COLUMN  "PEDIDO"."ESTADO" IS 'Estado en el que se encuentra el pedido: EP: en proceso, PG: pagado, ET: entregado'
;

COMMENT ON COLUMN  "PEDIDO"."FECHA" IS 'Fecha en que se realizo el pedido'
;

COMMENT ON COLUMN  "PEDIDO"."CALIFICACION" IS 'Calificacion que se le da al representante de ventas despues de hacer el pedido'
;

COMMENT ON COLUMN  "PRODUCTO"."ID_PRODUCTO" IS 'Identificacion del producto'
;

COMMENT ON COLUMN  "PRODUCTO"."NOMBRE" IS 'Nombre del producto'
;

COMMENT ON COLUMN  "PRODUCTO"."ID_CATEGORIA" IS 'Id la categoria a la cual pertenece le producto'
;

COMMENT ON COLUMN  "PRODUCTO"."VALOR" IS 'Valor unitario del producto'
;

COMMENT ON COLUMN  "PRODUCTO"."DETALLE" IS 'Detalle del producto'
;

COMMENT ON COLUMN  "PRODUCTO"."IVA" IS 'Iva asociado al producto'
;

COMMENT ON COLUMN  "PSE"."ID_PSE" IS 'Identificacion de PSE'
;

COMMENT ON COLUMN  "PSE"."CEDULA_CLIENTE" IS 'Cedula asociada a una cuenta PSE'
;

COMMENT ON COLUMN  "PSE"."CONTRASENA" IS 'Contraseña de la cuenta PSE'
;

COMMENT ON COLUMN  "REGION_PRODUCTO"."ID_UBICACION" IS 'Identificacion de la ubicacion asociado a un inventario'
;

COMMENT ON COLUMN  "REGION_PRODUCTO"."ID_PRODUCTO" IS 'Identificacion del producto asociado a un inventario'
;

COMMENT ON COLUMN  "REGION_PRODUCTO"."CANTIDAD" IS 'Cantidad del producto en inventario'
;

COMMENT ON COLUMN  "REGION_PRODUCTO"."ESTADO" IS 'Estado del producto en Stock: AGOTADO, DISPONIBLE'
;

COMMENT ON COLUMN  "REP_VENTA_CLIENTE"."CEDULA_CLIENTE" IS 'Identificacion del cliente'
;

COMMENT ON COLUMN  "REP_VENTA_CLIENTE"."CEDULA_REPRESENTANTE" IS 'Identificacion del representante de ventas'
;

COMMENT ON COLUMN  "REP_VENTA_CLIENTE"."FECHA_INICIAL" IS 'Fecha inicial del periodo en el cual un cliente tuvo a un determinado representante de ventas'
;

COMMENT ON COLUMN  "REP_VENTA_CLIENTE"."FECHA_FINAL" IS 'Fecha final del periodo en el cual un cliente tuvo a un determinado representante de ventas'
;

COMMENT ON COLUMN  "REPRESENTANTE_VENTA"."CEDULA_REPRESENTANTE" IS 'Identificacion del representante de ventas'
;

COMMENT ON COLUMN  "REPRESENTANTE_VENTA"."NOMBRE" IS 'Nombre del representante de ventas'
;

COMMENT ON COLUMN  "REPRESENTANTE_VENTA"."APELLIDO" IS 'Apellido del representante de ventas'
;

COMMENT ON COLUMN  "REPRESENTANTE_VENTA"."TELEFONO" IS 'Telefono del representante de ventas'
;

COMMENT ON COLUMN  "REPRESENTANTE_VENTA"."CONTRASENA" IS 'Cotraseña con la cual el representante de ventas se loguea en el sistema'
;

COMMENT ON COLUMN  "REPRESENTANTE_VENTA"."ID_UBICACION" IS 'Codigo de la region a la cual pertenece el representante de ventas'
;

COMMENT ON COLUMN  "REPRESENTANTE_VENTA"."ID_REP_SUPERIOR" IS 'Codigo del representante de ventas superior que ingreso al representante de ventas'
;

COMMENT ON COLUMN  "TARJETA"."ID_TARJETA" IS 'Identificacion de la tarjeta'
;

COMMENT ON COLUMN  "TARJETA"."NUMERO" IS 'Numero de identificacion unico ligado a la tarjeta'
;

COMMENT ON COLUMN  "TARJETA"."CEDULA_CLIENTE" IS 'Cedula del cliente que posee una tarjeta'
;

COMMENT ON COLUMN  "TARJETA"."CVC" IS ' Codigo de verificación unico de la tarjeta'
;

COMMENT ON COLUMN  "TARJETA"."FECHA_VENCIMIENTO" IS 'Fecha de caducidad de la tarjeta'
;

COMMENT ON COLUMN  "UBICACION"."ID_UBICACION" IS 'Identificacion de la ubicacion'
;

COMMENT ON COLUMN  "UBICACION"."NOMBRE" IS 'Nombre de la ubicacion'
;

COMMENT ON COLUMN  "UBICACION"."ID_SUPER" IS 'Codigo del pais al cual pertenece la region'
;

COMMENT ON COLUMN  "UBICACION"."ID_DIRECTOR" IS 'Codigo del representante de ventas con el cargo de director de esa region'
;

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

ALTER TABLE  "CATEGORIA" 
 ADD CONSTRAINT "PK_CATEGORIA"
	PRIMARY KEY ("ID_CATEGORIA") 
 USING INDEX
;

ALTER TABLE  "CLASIFICACION" 
 ADD CONSTRAINT "PK_CLASIFICACION"
	PRIMARY KEY ("ID_CLASIFICACION") 
 USING INDEX
;

ALTER TABLE  "CLASIFICACION" 
 ADD CONSTRAINT "CK_VALIDAR_CATEGORIA" CHECK (CATEGORIA IN ('BG', 'JN', 'SN', 'MS'))
;

ALTER TABLE  "CLASIFICACION" 
 ADD CONSTRAINT "CK_VALIDAR_V_INICIAL" CHECK (VALOR_INICIAL >= 0)
;

ALTER TABLE  "CLASIFICACION" 
 ADD CONSTRAINT "CK_VALIDAR_V_FINAL" CHECK (VALOR_FINAL > 0)
;

ALTER TABLE  "CLASIFICACION" 
 ADD CONSTRAINT "CK_VALIDAR_CLF_MIN" CHECK (CALIFICACION_MINIMA BETWEEN 1 AND 5)
;

ALTER TABLE  "CLASIFICACION" 
 ADD CONSTRAINT "CK_VALIDAR_COMISION" CHECK (COMISION > 0)
;

ALTER TABLE  "CLASIFICACION" 
 ADD CONSTRAINT "CK_VALIDAR_ID" CHECK (ID_CLASIFICACION IN (1,2,3,4))
;

ALTER TABLE  "CLIENTE" 
 ADD CONSTRAINT "PK_CLIENTE"
	PRIMARY KEY ("CEDULA_CLIENTE") 
 USING INDEX
;

ALTER TABLE  "DETALLE_PRODUCTO" 
 ADD CONSTRAINT "PK_DETALL_PRODUCT"
	PRIMARY KEY ("ID_PEDIDO","ID_PRODUCTO") 
 USING INDEX
;

ALTER TABLE  "DETALLE_PRODUCTO" 
 ADD CONSTRAINT "CK_VALIDAR_CANTIDAD_P" CHECK (CANTIDAD > 0)
;

ALTER TABLE  "DETALLE_PRODUCTO" 
 ADD CONSTRAINT "CK_VALIDAR_TOTAL" CHECK (TOTAL_PRODUCTO > 0)
;

ALTER TABLE  "HISTORICO_CLASIFICACION" 
 ADD CONSTRAINT "PK_HISTORICO_REP"
	PRIMARY KEY ("CEDULA_REPRESENTANTE","ID_CLASIFICACION") 
 USING INDEX
;

ALTER TABLE  "HISTORICO_CLASIFICACION" 
 ADD CONSTRAINT "CK_VALIDAR_VENTA" CHECK (VENTA > 0)
;

ALTER TABLE  "HISTORICO_CLASIFICACION" 
 ADD CONSTRAINT "CK_VALIDAR_CLSFCN" CHECK (CALIFICACION >= 0 AND CALIFICACION <= 5)
;

ALTER TABLE  "PAGO" 
 ADD CONSTRAINT "PK_PAGO"
	PRIMARY KEY ("ID_PAGO") 
 USING INDEX
;

ALTER TABLE  "PEDIDO" 
 ADD CONSTRAINT "PK_PEDIDO"
	PRIMARY KEY ("ID_PEDIDO") 
 USING INDEX
;

ALTER TABLE  "PEDIDO" 
 ADD CONSTRAINT "CK_VALIDAR_TOTAL_P" CHECK (TOTAL_PEDIDO > 0)
;

ALTER TABLE  "PEDIDO" 
 ADD CONSTRAINT "CK_VALIDAR_ESTADO" CHECK (ESTADO IN ('EP', 'PG', 'ET'))
;

ALTER TABLE  "PEDIDO" 
 ADD CONSTRAINT "CK_VALIDAR_CALIFICACION" CHECK (CALIFICACION BETWEEN 0 AND 5)
;

ALTER TABLE  "PRODUCTO" 
 ADD CONSTRAINT "PK_PRODUCTO"
	PRIMARY KEY ("ID_PRODUCTO") 
 USING INDEX
;

ALTER TABLE  "PRODUCTO" 
 ADD CONSTRAINT "CK_VALIDAR_VALOR" CHECK (VALOR > 0)
;

ALTER TABLE  "PRODUCTO" 
 ADD CONSTRAINT "CK_VALIDAR_IVA" CHECK (IVA > 0)
;

ALTER TABLE  "PSE" 
 ADD CONSTRAINT "PK_PSE"
	PRIMARY KEY ("ID_PSE") 
 USING INDEX
;

ALTER TABLE  "PSE" 
 ADD CONSTRAINT "UK_CEDULA" UNIQUE ("CEDULA_CLIENTE")
;

ALTER TABLE  "REGION_PRODUCTO" 
 ADD CONSTRAINT "PK_UBICACION_PR"
	PRIMARY KEY ("ID_UBICACION","ID_PRODUCTO") 
 USING INDEX
;

ALTER TABLE  "REGION_PRODUCTO" 
 ADD CONSTRAINT "CK_VALIDAR_CANTIDAD" CHECK (CANTIDAD >= 0)
;

ALTER TABLE  "REGION_PRODUCTO" 
 ADD CONSTRAINT "CK_VALIDAR_ESTADO_P" CHECK (ESTADO IN ('AGOTADO', 'DISPONIBLE'))
;

ALTER TABLE  "REP_VENTA_CLIENTE" 
 ADD CONSTRAINT "PK_REP_VENTA_CL"
	PRIMARY KEY ("CEDULA_CLIENTE","CEDULA_REPRESENTANTE") 
 USING INDEX
;

ALTER TABLE  "REPRESENTANTE_VENTA" 
 ADD CONSTRAINT "PK_REPRESENTANT"
	PRIMARY KEY ("CEDULA_REPRESENTANTE") 
 USING INDEX
;

ALTER TABLE  "TARJETA" 
 ADD CONSTRAINT "PK_TARJETA"
	PRIMARY KEY ("ID_TARJETA") 
 USING INDEX
;

ALTER TABLE  "TARJETA" 
 ADD CONSTRAINT "UK_NUMERO" UNIQUE ("NUMERO")
;

ALTER TABLE  "UBICACION" 
 ADD CONSTRAINT "PK_UBICACION"
	PRIMARY KEY ("ID_UBICACION") 
 USING INDEX
;

/* Create Foreign Key Constraints */

ALTER TABLE  "CATEGORIA" 
 ADD CONSTRAINT "FK_SUPER_CATEGORY"
	FOREIGN KEY ("SUPERCATEGORIA") REFERENCES  "CATEGORIA" ("ID_CATEGORIA")
;

ALTER TABLE  "DETALLE_PRODUCTO" 
 ADD CONSTRAINT "FK_DETALLE_PRODUCTO_PD"
	FOREIGN KEY ("ID_PEDIDO") REFERENCES  "PEDIDO" ("ID_PEDIDO")
;

ALTER TABLE  "DETALLE_PRODUCTO" 
 ADD CONSTRAINT "FK_DETALLE_PRODUCTO_PR"
	FOREIGN KEY ("ID_PRODUCTO") REFERENCES  "PRODUCTO" ("ID_PRODUCTO")
;

ALTER TABLE  "HISTORICO_CLASIFICACION" 
 ADD CONSTRAINT "FK_HISTORICO_CLASIFICA"
	FOREIGN KEY ("ID_CLASIFICACION") REFERENCES  "CLASIFICACION" ("ID_CLASIFICACION")
;

ALTER TABLE  "HISTORICO_CLASIFICACION" 
 ADD CONSTRAINT "FK_HISTORICO_REP_VENTA"
	FOREIGN KEY ("CEDULA_REPRESENTANTE") REFERENCES  "REPRESENTANTE_VENTA" ("CEDULA_REPRESENTANTE")
;

ALTER TABLE  "PAGO" 
 ADD CONSTRAINT "FK_PAGO_PSE"
	FOREIGN KEY ("ID_PSE") REFERENCES  "PSE" ("ID_PSE")
;

ALTER TABLE  "PAGO" 
 ADD CONSTRAINT "FK_PAGO_TARJETA"
	FOREIGN KEY ("ID_TARJETA") REFERENCES  "TARJETA" ("ID_TARJETA")
;

ALTER TABLE  "PEDIDO" 
 ADD CONSTRAINT "FK_PEDIDO_CLIENTE"
	FOREIGN KEY ("CEDULA_CLIENTE") REFERENCES  "CLIENTE" ("CEDULA_CLIENTE")
;

ALTER TABLE  "PEDIDO" 
 ADD CONSTRAINT "FK_PEDIDO_PAGO"
	FOREIGN KEY ("ID_PAGO") REFERENCES  "PAGO" ("ID_PAGO")
;

ALTER TABLE  "PRODUCTO" 
 ADD CONSTRAINT "FK_PRODUCT_CATEGORY"
	FOREIGN KEY ("ID_CATEGORIA") REFERENCES  "CATEGORIA" ("ID_CATEGORIA")
;

ALTER TABLE  "PSE" 
 ADD CONSTRAINT "FK_PSE_CLIENTE"
	FOREIGN KEY ("CEDULA_CLIENTE") REFERENCES  "CLIENTE" ("CEDULA_CLIENTE")
;

ALTER TABLE  "REGION_PRODUCTO" 
 ADD CONSTRAINT "FK_PRODUCTO_REGION"
	FOREIGN KEY ("ID_PRODUCTO") REFERENCES  "PRODUCTO" ("ID_PRODUCTO")
;

ALTER TABLE  "REGION_PRODUCTO" 
 ADD CONSTRAINT "FK_UBICACION_REGION"
	FOREIGN KEY ("ID_UBICACION") REFERENCES  "UBICACION" ("ID_UBICACION")
;

ALTER TABLE  "REP_VENTA_CLIENTE" 
 ADD CONSTRAINT "FK_REP_VENTA_CL_REP"
	FOREIGN KEY ("CEDULA_REPRESENTANTE") REFERENCES  "REPRESENTANTE_VENTA" ("CEDULA_REPRESENTANTE")
;

ALTER TABLE  "REP_VENTA_CLIENTE" 
 ADD CONSTRAINT "FK_REP_VENTA_CLIENTE_CL"
	FOREIGN KEY ("CEDULA_CLIENTE") REFERENCES  "CLIENTE" ("CEDULA_CLIENTE")
;

ALTER TABLE  "REPRESENTANTE_VENTA" 
 ADD CONSTRAINT "FK_REP_VENTA_SUPERIOR"
	FOREIGN KEY ("ID_REP_SUPERIOR") REFERENCES  "REPRESENTANTE_VENTA" ("CEDULA_REPRESENTANTE")
;

ALTER TABLE  "REPRESENTANTE_VENTA" 
 ADD CONSTRAINT "FK_REP_VENTA_UBICACION"
	FOREIGN KEY ("ID_UBICACION") REFERENCES  "UBICACION" ("ID_UBICACION")
;

ALTER TABLE  "TARJETA" 
 ADD CONSTRAINT "FK_TARJETA_CLIENTE"
	FOREIGN KEY ("CEDULA_CLIENTE") REFERENCES  "CLIENTE" ("CEDULA_CLIENTE")
;

ALTER TABLE  "UBICACION" 
 ADD CONSTRAINT "FK_DIRECTOR_REGION"
	FOREIGN KEY ("ID_DIRECTOR") REFERENCES  "REPRESENTANTE_VENTA" ("CEDULA_REPRESENTANTE")
;

ALTER TABLE  "UBICACION" 
 ADD CONSTRAINT "FK_PAIS_REGION"
	FOREIGN KEY ("ID_SUPER") REFERENCES  "UBICACION" ("ID_UBICACION")
;
